### ISSUE TITLE
VCV Rack crashes when loading Interzone

### ISSUE THREAD

**Issue by FenderBaba** [ValleyAudio/ValleyRackFree#53] opened 2020-10-02 12:39 UTC
After the latest update today, the load of Interzone crashes the Rack. Trying with a complete empty Rack produced the attached logfile. 
[log.txt](https://github.com/ValleyAudio/ValleyRackFree/files/5317943/log.txt)
Regards
Remo

**Comment by ValleyAudio** [comment] 2020-10-02 12:47
Is this behaviour quite recent? As only as of today started crashing?

**Comment by ValleyAudio** [comment] 2020-10-02 13:33
@FenderBaba I cannot seem to recreate this issue as it loads fine on my non-development Windows system.

**Comment by FenderBaba** [comment] 2020-10-02 16:31
Very strange. What can I do to investigate/solve the problem ?
I'm working on a i7 PC, 8GB Ram with Windows 10 2004 with all the latest patches. 
I will do some deeper investigation on my machine, later

**Comment by tarnith** [comment] 2020-10-02 18:41
I can also reproduce this issue. 
1. Open VCV Rack
2. Right-click open module menu
3. Click Interzone

![image](https://user-images.githubusercontent.com/10873011/94958253-134ea180-04a4-11eb-8d48-12596bee8e01.png)
[log.txt](https://github.com/ValleyAudio/ValleyRackFree/files/5319707/log.txt)
![image](https://user-images.githubusercontent.com/10873011/94958098-cbc81580-04a3-11eb-921d-c87f952520f2.png)
Windows 10 Pro 1909

**Comment by ValleyAudio** [comment] 2020-10-03 00:04
The issue seems to be caused by the compiler for the Windows version of my plugin. A lot of other devs such as Bogaudio and Frozen Wasteland ran into this exact issue where a random number generator module used for noise generation crashes in Windows. I've added a workaround that Bogaudio found, so you'll have to sit tight for now until the VCV library team upload my fixed version of the plugin.

**Comment by FenderBaba** [comment] 2020-10-03 06:06
Thank You very much for the effort. The time will come and everything will be good ;-)
Best regards
Remo

**Comment by ValleyAudio** [comment] 2020-10-09 12:29
Issue fixed in v1.1.3

**Closed by ValleyAudio** 2020-10-09 12:29 UTC
